import { Live2DCubismFramework as icubismmodelsetting } from "./icubismmodelsetting";
import { Live2DCubismFramework as cubismid } from "./id/cubismid";
import { Live2DCubismFramework as cubismjson } from "./utils/cubismjson";
import { Live2DCubismFramework as csmmap } from "./type/csmmap";
import csmMap = csmmap.csmMap;
import CubismIdHandle = cubismid.CubismIdHandle;
import CubismJson = cubismjson.CubismJson;
import ICubismModelSetting = icubismmodelsetting.ICubismModelSetting;
export declare namespace Live2DCubismFramework {
    class CubismModelSettingJson extends ICubismModelSetting {
        constructor(buffer: ArrayBuffer, size: number);
        release(): void;
        GetJson(): CubismJson;
        getModelFileName(): string;
        getTextureCount(): number;
        getTextureDirectory(): string;
        getTextureFileName(index: number): string;
        getHitAreasCount(): number;
        getHitAreaId(index: number): CubismIdHandle;
        getHitAreaName(index: number): string;
        getPhysicsFileName(): string;
        getPoseFileName(): string;
        getExpressionCount(): number;
        getExpressionName(index: number): string;
        getExpressionFileName(index: number): string;
        getMotionGroupCount(): number;
        getMotionGroupName(index: number): string;
        getMotionCount(groupName: string): number;
        getMotionFileName(groupName: string, index: number): string;
        getMotionSoundFileName(groupName: string, index: number): string;
        getMotionFadeInTimeValue(groupName: string, index: number): number;
        getMotionFadeOutTimeValue(groupName: string, index: number): number;
        getUserDataFile(): string;
        getLayoutMap(outLayoutMap: csmMap<string, number>): boolean;
        getEyeBlinkParameterCount(): number;
        getEyeBlinkParameterId(index: number): CubismIdHandle;
        getLipSyncParameterCount(): number;
        getLipSyncParameterId(index: number): CubismIdHandle;
        private isExistModelFile;
        private isExistTextureFiles;
        private isExistHitAreas;
        private isExistPhysicsFile;
        private isExistPoseFile;
        private isExistExpressionFile;
        private isExistMotionGroups;
        private isExistMotionGroupName;
        private isExistMotionSoundFile;
        private isExistMotionFadeIn;
        private isExistMotionFadeOut;
        private isExistUserDataFile;
        private isExistEyeBlinkParameters;
        private isExistLipSyncParameters;
        private _json;
        private _jsonValue;
    }
}
